export const TRANSLATE_API = "TRANSLATE_API"
export const TRANSLATE_AI_API = "TRANSLATE_AI_API"
export const TRANSLATE_NUMBER_API = "TRANSLATE_NUMBER_API"
export const TRANSLATE_FILE_API = "TRANSLATE_FILE_API"